# Generated by Django 5.1.2 on 2024-11-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0002_alter_board_name_alter_column_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='order',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
