# Generated by Django 5.1.2 on 2024-11-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0003_alter_column_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
