# Generated by Django 5.1.2 on 2024-11-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0004_board_finished_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
