# Generated by Django 5.1.2 on 2024-11-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0005_alter_board_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='order',
            field=models.PositiveIntegerField(),
        ),
    ]
