# Generated by Django 5.1.2 on 2024-10-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab2_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='surname',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
