# Generated by Django 5.1.2 on 2024-10-17 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab2_app', '0002_person_surname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stanowisko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=32)),
                ('opis', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=64)),
                ('nazwisko', models.CharField(max_length=128)),
                ('plec', models.CharField(choices=[('M', 'Mężczyzna'), ('K', 'Kobieta'), ('INNE', 'Inne')], max_length=8)),
                ('stanowisko', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab2_app.stanowisko')),
            ],
        ),
    ]
