# Generated by Django 5.1.2 on 2024-10-17 12:29

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab2_app', '0003_stanowisko_osoba'),
    ]

    operations = [
        migrations.AddField(
            model_name='osoba',
            name='data_dodania',
            field=models.DateField(db_default=django.db.models.functions.datetime.Now()),
        ),
    ]
