# Generated by Django 5.1.2 on 2024-10-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab2_app', '0004_osoba_data_dodania'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='plec',
            field=models.IntegerField(choices=[(0, 'Inne'), (1, 'Mezczyzna'), (2, 'Kobieta')]),
        ),
    ]
