# Generated by Django 5.1.2 on 2024-10-23 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab2_app', '0005_alter_osoba_plec'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'ordering': ['nazwisko']},
        ),
    ]
